title: "Django Channels 実践チュートリアル ～ Django ChannelsとDockerで作る非同期アプリケーション入門 ～"
summary: "Djangoにおいて非同期通信を行うためのライブラリである、Django Channelsを使ってwebsocketを用いた非同期アプリケーションのデプロイまで行います。"
topics: ["Django","channels","非同期通信","チュートリアル"]
published: false
price: 0
chapters:
  - introduction
  - chapter01
  - chapter02
  - appendix
